FuelLabs/fuel-connectors

.changeset/clever-otters-juggle.md
.changeset/config.json
.changeset/gentle-eggs-change.md
.github/workflows/update-sdk-cron.yaml
.lintstagedrc
examples/nodejs/package.json
examples/nodejs/src/index.ts
examples/nodejs/tsconfig.json
examples/nodejs/tsup.config.js
examples/react-app/package.json
package.json
packages/connectors/package.json
packages/connectors/tsup.config.js
packages/fuel-development-wallet/package.json
packages/fuel-wallet/package.json
packages/fuelet-wallet/package.json
pnpm-lock.yaml

- Add a `NodeJS` on `examples` folder to make it easier to test bundle size without any external frontend frameworks.
- Add automatic `update/sdk` CI to keep SDK always up-to-date.
- Remove redundant packages from the umbrella package (`@fuels/connectors`)

chore: remove redundant packages and add nodejs example

---

examples/react-app/src/components/contract-link.tsx
examples/react-app/src/components/counter.tsx
examples/react-app/src/components/transfer.tsx
examples/react-app/src/hooks/useWallet.ts
packages/evm-connector/src/EvmWalletConnector.ts

fix: UI and wallets improvements

---

examples/react-app/index.html

Add the proper URL for the favicon.
Some web applications are not able to get the right URL if we're using relative path.

fix: favicon

---

.changeset/famous-bears-shout.md
examples/react-app/src/main.tsx
examples/react-next/src/components/Providers.tsx
packages/connectors/package.json
packages/connectors/src/defaultConnectors.ts
packages/connectors/src/evm-connector/index.ts
packages/connectors/src/index.ts
packages/connectors/src/walletconnect-connector/index.ts
packages/connectors/tsup.config.js

Since we also use this library in service workers, we can't bundle together libraries that depend on the Node.js environment.
From now on, we'll export `WalletConnect` and `EVM connectors` using a specific-path, example:
```tsx
import { WalletConnectConnector } from '@fuels/connectors/walletconnect';
```

fix: export walletconnect and evm separate

---

.changeset/forty-timers-heal.md
packages/connectors/src/defaultConnectors.ts

- remove bakoSafe from defaultConnectors for now
- revert versioning of `bakoSafe` from major to minor
reasoning is that the connector API is still not stable and sometimes breaking the flow

chore: remove bakoSafe from `defaultConnectors`

---

.changeset/violet-grapes-matter.md
examples/react-app/src/components/counter.tsx
packages/walletconnect-connector/src/WalletConnectConnector.ts
packages/walletconnect-connector/src/utils/Predicate.ts

- Closes #109 
- Closes #124 
- make transactions work without needing to inform specific `gasLimit` or/and `maxFee`
- improve fee estimation before get the `txId` to sign on eth wallet. this way the `maxFee` won't change later after applying the witness
- create a fake predicate and make it return true to get the `gasUsed` by a valid predicate and add it in fee preemptively 
thanks @luizstacio for some help on this one 🚀

fix: transaction fees of walletConnectConnector

---

examples/react-app/src/App.tsx
examples/react-app/src/components/notification.tsx

- make integration link don't take whole link
- avoid one button inside of other button

fix: layout fixes in example react-app

---

package.json

Remove this coverage requirements for now as:
- connectors tests are implemented by the own connector, simply having coverage doesn't guarantee that it will work
- next task coming up is to implement a more reliable e2e tests that will guarantee that each connector works. With this we don't need this unit tests inside each connector anymore

chore: remove coverage requirements

---

.changeset/thick-squids-compete.md
packages/burner-wallet-connector/src/BurnerWalletConnector.ts
packages/burner-wallet-connector/src/InMemoryStorage.ts
packages/connectors/src/defaultConnectors.ts

Closes #107 
- [Add support for burner wallet config on default connectors](https://github.com/FuelLabs/fuel-connectors/commit/fb845c0cfdfccfda60637af8d405964e9efbdecb)
- [Burner wallet storage not working on nodejs](https://github.com/FuelLabs/fuel-connectors/commit/bbf19a2f8b6faeafc5c99055fe2ce2beb2988400)
- [Create in memory storage on burner wallet](https://github.com/FuelLabs/fuel-connectors/commit/242b24f84f4ac35dba9c1332cb46c80bac5f4766)
Observation: Burner Wallet's Storage will not persist information between executions on Vercel or Node.js env.
Successful Explorer build with Burner Wallet enabled, using this PR's tag:
https://vercel.com/fuel-labs/fuel-explorer/Goc1QWM49AGSHvhTiF2xUbxYhFJA

fix: burner wallet storage incompatibility with Node.js env

---

.changeset/red-eagles-deny.md
packages/react/package.json
pnpm-lock.yaml

`@types/react` was previously installed as a dependency in `@fuels/react`, which caused issues when using a different React version in external projects. 
Now, the local `@types/react` declarations will be used.
| 📷  Demo |
| --- |
| <img width="949" alt="react v" src="https://github.com/user-attachments/assets/f0f25925-629b-439d-8b35-e00ef40972eb"> |

fix: remove react types from @fuels/react

---

.changeset/proud-books-think.md
packages/react/src/ui/Connect/index.tsx
packages/react/src/ui/Connect/styles.tsx

The `Connect` modal had a `z-index` issue because it was rendered directly inside the actual content in the`body`. 
This caused it to be `hidden` behind other dialogs that use `Portals` in external projects.
---
| 📷 Demo |
| --- |
| <img width="573" alt="Screenshot 2024-09-20 at 13 18 10" src="https://github.com/user-attachments/assets/01b57f32-1ba8-44a3-8baa-745abe04ce88"> |

fix: render connect modal using portal

---

.changeset/shy-timers-doubt.md
packages/react/src/ui/Connect/components/Connector/Connecting.tsx
packages/react/src/ui/Connect/components/Connector/Connector.tsx

- Closes https://github.com/FuelLabs/fuel-connectors/issues/300
---
The issue was caused by relying on the react-query cache, which could lead to inconsistencies since app consumers might have custom configurations.
I also took the opportunity to replace those simple `useQueries` with `useEffect`, as it’s a better and safer approach for this case.

fix: ensure user is already connected 

---

.changeset/brave-students-boil.md
examples/react-app/src/main.tsx
packages/react/src/providers/FuelProvider.tsx
packages/react/src/providers/FuelUIProvider.tsx

- If a dynamically created obj (i.e. loosely created during render) is passed to a Providers's Context, it triggers a new render on all children + components accessing the context via `useContext`. It can also trigger unnecessary cycles in useMemo/useCallback/useEffect that uses properties from the context.
- Wrapped Provider's obj data + dependencies in useMemo/useCallback

fix: FuelProvider leaking render events

---

.changeset/beige-peaches-burn.md
packages/react/src/core/useNamedQuery.ts
packages/react/src/hooks/useAccount.ts
packages/react/src/hooks/useAccounts.ts
packages/react/src/hooks/useAssets.ts
packages/react/src/hooks/useBalance.ts
packages/react/src/hooks/useChain.ts
packages/react/src/hooks/useConnectors.ts
packages/react/src/hooks/useContractRead.ts
packages/react/src/hooks/useCurrentConnector.tsx
packages/react/src/hooks/useIsConnected.ts
packages/react/src/hooks/useIsSupportedNetwork.tsx
packages/react/src/hooks/useNetwork.ts
packages/react/src/hooks/useNetworks.ts
packages/react/src/hooks/useNodeInfo.ts
packages/react/src/hooks/useProvider.ts
packages/react/src/hooks/useTransaction.ts
packages/react/src/hooks/useTransactionReceipts.ts
packages/react/src/hooks/useTransactionResult.ts
packages/react/src/hooks/useWallet.ts

- Closes https://github.com/FuelLabs/fuel-connectors/issues/322
---
As per the official [React Query documentation](https://tanstack.com/query/latest/docs/framework/react/guides/initial-query-data#using-initialdata-to-prepopulate-a-query), `initialData` is not intended for prepopulating queries, as it persists data in the cache.
This is important because when a consumer app configures a `QueryClient` with `staleTime: Infinity`, the data won't be refetched, even when components re-render. This behavior is due to how react-query handles its cache mechanism.
To properly set initial (but pending) data, the correct method is to use `placeholderData` instead.
Also, to complement that, I did a small update in the `useNamedQuery` to keep our typescript definitions compatible everywhere.

fix: conflicts with connected status in the cache engine

---

.changeset/gorgeous-dingos-study.md
packages/docs/.typedoc/hooks-links.json
packages/react/src/providers/FuelHooksProvider.tsx
packages/react/src/providers/FuelProvider.tsx
packages/react/src/ui/Connect/components/Network/NetworkDialog.tsx
packages/react/src/utils/queryKeys.ts
packages/react/src/utils/useWindowConnectorEvent.ts

On this PR https://github.com/FuelLabs/fuels-ts/commit/3b59f1fba06d4d2e4884c03bb5e77388394f2b32
The event listeners for global target on delayed to avoid race condition as this would set the first connector to respond tu this event as current connector.
This assumption was correct, but we should change to first listen the global target events, and than check inside handler If the event received is the current connector on the storage if yes it should use it, and call selectConnector.
This PR creates a hook `useWindowConnectorEvent` that execute this behavior.

fix: delay start of current connector

---

.changeset/thirty-doors-pay.md
e2e-tests/package.json
examples/react-app/contracts/Forc.lock
examples/react-app/contracts/fuel-toolchain.toml
examples/react-app/package.json
examples/react-app/src/types/contracts/Counter.ts
examples/react-app/src/types/contracts/CounterFactory.ts
examples/react-app/src/types/contracts/index.ts
examples/react-next/package.json
packages/bako-safe/package.json
packages/burner-wallet-connector/package.json
packages/common/package.json
packages/connectors/package.json
packages/docs/package.json
packages/evm-connector/package.json
packages/evm-predicates/package.json
packages/evm-predicates/predicate/fuel-toolchain.toml
packages/fuel-development-wallet/package.json
packages/fuel-wallet/package.json
packages/fuelet-wallet/package.json
packages/react/package.json
packages/solana-connector/package.json
packages/solana-connector/predicate/fuel-toolchain.toml
packages/walletconnect-connector/package.json
pnpm-lock.yaml

- Updated `fuels` to `next` version
- Updated `fuel-core` to `0.38.0` version
- Updated `forc` to `0.65.2` version

chore: update versions

---

.changeset/lazy-apples-beg.md
examples/react-next/src/components/PageContet.tsx
packages/common/src/PredicateConnector.ts
packages/common/src/test/testConnector.ts
packages/common/src/types.ts
packages/connectors/src/createConfig.ts
packages/evm-connector/src/EvmWalletConnector.ts
packages/solana-connector/src/SolanaConnector.ts
packages/walletconnect-connector/src/WalletConnectConnector.ts

This PR adds a signMessageCustomCurve that, if it exists, can be used to sign messages using the underlying connector application. This signature can return any type of signature; because of this, the object returned includes the `curve` and `signature`.
```ts
const { wallet } = useWallet();
const { currentConnector } = useCurrentConnector();
if (hasSignMessageCustomCurve(currentConnector)) {
const { curve, signature } =
await currentConnector.signMessageCustomCurve(message);
setSignature(`${curve} signature - ${signature}`);
} else if (wallet) {
const signature = await wallet.signMessage(message);
setSignature(`Native signature - ${signature}`);
}
```

feat: add sign message custom curves

---

.changeset/tricky-lemons-yell.md
packages/bako-safe/src/BakoSafeConnector.ts
packages/bako-safe/src/constants.ts

This PR fixes the issue when creating a transaction and receiving the event from a previous transaction.
The problem was that the event emitter was storing the listeners from previous transactions. The `.on` was replaced with `.once` since the events need to be listened to only within the context of each method.
This PR also includes this fix: https://github.com/FuelLabs/fuel-connectors/pull/323

fix(bako-safe): prevents events from remaining active

---

.changeset/strong-bugs-remain.md
packages/connectors/src/defaultConnectors.ts
packages/walletconnect-connector/src/WalletConnectConnector.ts
packages/walletconnect-connector/src/types.ts

When you have wagmi provider configured on the dapp, the reconnection of the Fuel Connector may conflict with reconnection of Wagmi, causing flaky loss of section across refreshs.
Skip the auto reconnect step on WalletConnectConnector, this way we let the responsibility of recovering session after refresh for Wagmi, which will do it anyway.

feat: add skip auto reconnect

---

e2e-tests/react-next/package.json

Turbo was breaking main release
```
"build": {
"dependsOn": ["^build"],
"outputs": ["dist/**"]
```

chore(e2e): remove build script from package.json

---

README.md
e2e-tests/runner/package.json
package.json
turbo.json

This PR updates the documentation and provides a new script command to simplify the process of running end-to-end (E2E) tests locally.
- Updated the README to include detailed steps for running E2E tests locally.
- Added a new npm script command to streamline the local testing setup.
```
pnpm test:e2e
```

docs(e2e): Add instructions and command for running tests locally FE-897

---

.changeset/swift-knives-thank.md
.github/workflows/pr.yaml
e2e-tests/runner/common/common.ts
e2e-tests/runner/common/types.ts
e2e-tests/runner/examples/connectors/SolanaConnector/SolanaConnector.test.ts
e2e-tests/runner/examples/connectors/WalletConnectConnector/WalletConnectConnector.test.ts
e2e-tests/runner/package.json
package.json
packages/react/src/ui/Connect/components/ExternalDisclaimer/ExternalDisclaimer.tsx
packages/walletconnect-connector/src/WalletConnectConnector.ts

- Closes https://github.com/FuelLabs/fuel-connectors/issues/409

feat: skip EVM signature message

---

.changeset/cool-deers-love.md
packages/solana-connector/src/SolanaConnector.ts
packages/walletconnect-connector/src/WalletConnectConnector.ts

Order the svm/evm predicates by most recent first on the new helper methods

fix: on new helper methods, sort evm/svm predicates by more recent first

---

.changeset/afraid-foxes-cough.md
packages/common/src/PredicateConnector.ts
packages/walletconnect-connector/src/WalletConnectConnector.ts

- Closes #490 
- Closes FE-1515
The logic to detect the current predicate address was using only ETH balance in consideration. Now it's considering also another balances

fix: predicate selection logic consider balances instead of eth balance only

---

.github/workflows/pr-release.yaml

- Closes #494 
- Closes FE-1518
Change our `release PR to npm` action to use aws npm registry instead of npm directly.

feat: release pr tag on npm aws registry

---

.changeset/config.json

This PR updates the version in `e2e-tests/runner/package.json` to align it with the rest of the monorepo packages. This is a maintenance change for consistency and does not impact any published or user-facing code.
_None._

chore: update changeset configuration to include @e2e-tests/runner 
