FuelLabs/fuel-connectors

- .changeset/pretty-paws-mate.md
- examples/react-app/index.html
- examples/react-app/package.json
- examples/react-app/src/App.css
- examples/react-app/src/App.tsx
- examples/react-app/src/main.tsx
- packages/connectors/src/defaultConnectors.ts
- pnpm-lock.yaml
Improve demo UI for adding a live demo link.
> feat: update demo UI

- packages/fuel-wallet/src/types.ts
Export missing types to use on wallet-world.
> feat: export message types

- .github/workflows/release-npm.yaml
- .github/workflows/unpublish-npm.yaml
- scripts/unpublish.js
- Publish `next` tag instead of `rc`
- Add `unpublish` script
> ci: add next tag

- package.json
- pnpm-lock.yaml
Add missing package to the `unpublish` stuff
> fix: add missing package

- .changeset/dull-dancers-stare.md
- examples/nodejs/package.json
- examples/react-app/package.json
- packages/connectors/package.json
- packages/fuel-development-wallet/package.json
- packages/fuel-wallet/package.json
- packages/fuelet-wallet/package.json
- pnpm-lock.yaml
✨ This PR updates the SDK to tag latest
> feat: updating sdk to latest

- .changeset/smart-peas-live.md
- packages/connectors/tsup.config.js
Fix browser build compatibility issues by adding platform browser on the tsup config.
> fix: build for browser

- .changeset/gold-feet-burn.md
- packages/common/src/PredicateConnector.ts
- packages/common/src/types.ts
- packages/evm-connector/src/EvmWalletConnector.ts
- packages/solana-connector/src/SolanaConnector.ts
- packages/walletconnect-connector/src/WalletConnectConnector.ts
- Closes https://github.com/FuelLabs/fuel-connectors/issues/222
---
Remove automatic balance transfer between predicates when there are change outputs.
> fix: remove automatic balance transfer between predicates

- .changeset/early-windows-sit.md
- .changeset/mean-taxis-agree.md
- packages/react/src/hooks/useConnectors.ts
- packages/react/src/providers/FuelUIProvider.tsx
- Closes https://github.com/FuelLabs/fuel-connectors/issues/245
---
Sort connectors by name in the `Connect Wallet` modal.
| 📷  Demo |
| --- |
| <img width="388" alt="Screenshot 2024-09-10 at 10 58 38" src="https://github.com/user-attachments/assets/eb2c0701-9ee5-4d6c-bc54-94f4182b6ea1"> |
> feat: sort connector list by name

- .changeset/orange-toys-trade.md
- .changeset/swift-spies-wait.md
- package.json
- packages/react/package.json
- packages/react/src/providers/FuelUIProvider.tsx
- packages/react/src/ui/Connect/components/Connectors/ConnectorBadge.tsx
- packages/react/src/ui/Connect/components/Connectors/Connectors.tsx
- packages/react/src/ui/Connect/components/Connectors/styles.tsx
- packages/react/src/ui/Connect/themes.tsx
- turbo.json
- Closes https://github.com/FuelLabs/fuel-connectors/issues/247
---
| 📷  Demo |
| --- |
| <img width="372" alt="demo" src="https://github.com/user-attachments/assets/f042cb45-cf81-4dae-bf07-80254c08149e"> |
> feat: display installed and connected badges

- .changeset/tall-toys-burn.md
- packages/docs/src/guide/connectors/ethereum/evm-connector.md
- packages/docs/src/guide/connectors/ethereum/wagmiConfig.md
- packages/docs/src/guide/connectors/ethereum/wallet-connect.md
- packages/docs/src/guide/react-hooks/useBalance.md
- packages/docs/src/guide/with-react/fuel-provider/fuel-config.md
- packages/docs/src/guide/with-react/fuel-provider/theme.md
- packages/docs/src/guide/with-react/fuel-provider/ui.md
> fix: wrong import paths in docs

- .changeset/bright-cooks-study.md
- packages/react/src/hooks/useNetwork.ts
- packages/react/src/utils/queryKeys.ts
- Fixes not detecting wrong network on initial connection
- Fixes crash when Provider is null
> fix: not detecting wrong network on initial render

- .changeset/popular-parrots-boil.md
- packages/docs/src/guide/react-hooks/useNetwork.md
- packages/react/src/providers/FuelProvider.tsx
- packages/react/src/ui/Connect/components/Network/NetworkDialog.tsx
https://github.com/user-attachments/assets/eea5d237-f3a9-4414-98f0-94c75a482fdd
> fix: network switch dialog not hiding after wallet disconnection

- .changeset/light-colts-doubt.md
- .changeset/orange-suns-remember.md
- packages/walletconnect-connector/src/WalletConnectConnector.ts
- Fixed some EVM wallets rejecting sign message right after connection
> fix: some EVM wallets rejecting sign message right after connection

- examples/react-app/src/components/account.tsx
- Closes https://github.com/FuelLabs/fuel-connectors/issues/358
> feat: add explorer link FE-713

- .changeset/big-cherries-cough.md
- packages/solana-connector/src/web3Modal.ts
- packages/walletconnect-connector/src/web3Modal.ts
- Closes https://github.com/FuelLabs/fuel-ex-demo/issues/319
---
| 📷 EVM | SVM |
| --- | --- | 
| <img width="398" alt="Screenshot 2024-10-11 at 19 09 28" src="https://github.com/user-attachments/assets/367bb4f2-57a7-469a-9cb0-f58f20efc281"> | <img width="408" alt="Screenshot 2024-10-11 at 19 10 03" src="https://github.com/user-attachments/assets/c2aed1ce-6ecc-4016-9d7c-368e29a62208"> |
> feat: hide "all wallets" option in the EVM and SVM connectors

- packages/bako-safe/src/BakoSafeConnector.ts
- packages/bako-safe/src/SocketClient.ts
- packages/docs/src/guide/react-hooks/useIsSupportedNetwork.md
- packages/fuel-wallet/src/FuelWalletConnector.ts
Reverts FuelLabs/fuel-connectors#382
> revert: fix: node dynamic import error

- .changeset/cyan-hairs-tell.md
- packages/solana-connector/src/web3Modal.ts
Add missing changeset for this PR https://github.com/FuelLabs/fuel-connectors/pull/384
> docs: add missing changeset

- .changeset/hip-insects-suffer.md
- e2e-tests/package.json
- examples/react-app/package.json
- examples/react-next/package.json
- packages/bako-safe/package.json
- packages/burner-wallet-connector/package.json
- packages/common/package.json
- packages/connectors/package.json
- packages/docs/package.json
- packages/evm-connector/package.json
- packages/evm-predicates/package.json
- packages/fuel-development-wallet/package.json
- packages/fuel-wallet/package.json
- packages/fuelet-wallet/package.json
- packages/react/package.json
- packages/solana-connector/package.json
- packages/walletconnect-connector/package.json
- pnpm-lock.yaml
Upgrading `fuels` to `0.96.1`.
> chore!: upgrading `fuels` to `0.96.1`

- packages/react/src/hooks/useWallet.ts
I noticed this output in the console while testing sway playground.
> chore: Clean up console.log in useWallet.ts

- .changeset/angry-wolves-repair.md
- .changeset/purple-spoons-taste.md
- .changeset/stale-feet-speak.md
- .github/workflows/pr-release.yaml
- packages/common/src/PredicateFactory.ts
- packages/common/src/utils.ts
- packages/solana-connector/src/SolanaConnector.ts
- packages/walletconnect-connector/src/WalletConnectConnector.ts
- Closes #410 
- Closes https://linear.app/fuel-network/issue/FE-807/create-helper-to-svmevm-connectors
Including helper methods to get predicate address on fuel side coming from eth Address or svm Address
> feat: add util methods to convert address

- .github/pull_request_template.md
- .github/workflows/pr-release.yaml
- .github/workflows/release-npm-latest.yaml
- .github/workflows/release-npm-preview.yaml
- .github/workflows/release-npm.yaml
- .github/workflows/unpublish-npm.yaml
> chore: change env name npm

- .github/workflows/release-npm.yaml
> chore: change repo env

- .github/workflows/pr-release.yaml
> chore: Use variable for AWS region in workflow

- .changeset/fresh-geese-pay.md
- .changeset/khaki-swans-shave.md
- .changeset/tasty-cheetahs-leave.md
- e2e-tests/react-next/package.json
- e2e-tests/runner/package.json
- examples/react-app/package.json
- package.json
- packages/bako-safe/package.json
- packages/burner-wallet-connector/package.json
- packages/burner-wallet-connector/src/BurnerWalletConnector.ts
- packages/common/package.json
- packages/common/src/PredicateConnector.ts
- packages/connectors/package.json
- packages/docs/package.json
- packages/evm-connector/package.json
- packages/evm-predicates/package.json
- packages/fuel-development-wallet/package.json
- packages/fuel-wallet/package.json
- packages/fuel-wallet/src/FuelWalletConnector.ts
- packages/fuelet-wallet/package.json
- packages/react/package.json
- packages/solana-connector/package.json
- packages/solana-connector/src/SolanaConnector.ts
- packages/walletconnect-connector/package.json
- pnpm-lock.yaml
- Closes #514
- Closes FE-1627
> feat: support returning TransactionResponse when user calls sendTranssaction

- .changeset/orange-kids-rush.md
- packages/fuel-wallet/src/FuelWalletConnector.ts
> chore: add returnTransactionResponse flag to Fuel Wallet Connector

- .github/workflows/pr-tests.yml
- .github/workflows/setup-rust/action.yml
- docker/fuel-core/Dockerfile
- fuel-toolchain.toml
Attempt to fix the CI failures
> ci: fixed `fuel-core` versions
